//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities1 : DbContext
    {
        public BlogEntities1()
            : base("name=BlogEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<Tbl_ProjectCategory> Tbl_ProjectCategory { get; set; }
        public virtual DbSet<Tbl_Projects> Tbl_Projects { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Tbl_Services> Tbl_Services { get; set; }
        public virtual DbSet<Tbl_General_Details> Tbl_General_Details { get; set; }
        public virtual DbSet<Tbl_Team> Tbl_Team { get; set; }
        public virtual DbSet<FaceBookUser> FaceBookUsers { get; set; }
    }
}
