//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int Users_Id { get; set; }
        public long User_Role_Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Pwd { get; set; }
        public string CPwd { get; set; }
        public string Status_Code { get; set; }
    
        public virtual Tbl_Roles Tbl_Roles { get; set; }
    }
}
