//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Team
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public string Image { get; set; }
        public string Facebook_Url { get; set; }
        public string Twitter_Url { get; set; }
        public string Email { get; set; }
        public string LinkedIn_Url { get; set; }
        public string Skype_Url { get; set; }
    }
}
