//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_General_Details
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string GooglePlusURL { get; set; }
    }
}
