//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Services
    {
        public int Service_Id { get; set; }
        public string Service_Name { get; set; }
        public string Service_Description { get; set; }
    }
}
