//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Projects
    {
        public int Id { get; set; }
        public string P_Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
